#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : rubygem-cane
Version  : 2.6.2
Release  : 7
URL      : https://rubygems.org/downloads/cane-2.6.2.gem
Source0  : https://rubygems.org/downloads/cane-2.6.2.gem
Summary  : No detailed summary available
Group    : Development/Tools
License  : Apache-2.0
Requires: rubygem-cane-bin
BuildRequires : ruby
BuildRequires : rubygem-parallel
BuildRequires : rubygem-rake
BuildRequires : rubygem-rdoc
BuildRequires : rubygem-rspec-fire
BuildRequires : rubygem-simplecov

%description
# Cane
Fails your build if code quality thresholds are not met.
> Discipline will set you free.

%package bin
Summary: bin components for the rubygem-cane package.
Group: Binaries

%description bin
bin components for the rubygem-cane package.


%prep
gem unpack %{SOURCE0}
%setup -q -D -T -n cane-2.6.2
gem spec %{SOURCE0} -l --ruby > rubygem-cane.gemspec

%build
gem build rubygem-cane.gemspec

%install
%global gem_dir $(ruby -e'puts Gem.default_dir')
gem install -V \
--local \
--force \
--install-dir .%{gem_dir} \
--bindir .%{_bindir} \
cane-2.6.2.gem

mkdir -p %{buildroot}%{gem_dir}
cp -pa .%{gem_dir}/* \
%{buildroot}%{gem_dir}

if [ -d .%{_bindir} ]; then
mkdir -p %{buildroot}%{_bindir}
cp -pa .%{_bindir}/* \
%{buildroot}%{_bindir}/
fi


%files
%defattr(-,root,root,-)
/usr/lib64/ruby/gems/2.3.0/cache/cane-2.6.2.gem
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/HISTORY.md
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/LICENSE
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/README.md
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/bin/cane
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/cane.gemspec
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/abc_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/cli.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/cli/options.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/cli/parser.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/default_checks.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/doc_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/encoding_aware_iterator.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/file.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/json_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/rake_task.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/style_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/task_runner.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/threshold_check.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/version.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/lib/cane/violation_formatter.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/abc_check_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/cane_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/cli_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/doc_check_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/encoding_aware_iterator_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/file_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/json_formatter_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/parser_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/rake_task_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/runner_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/spec_helper.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/style_check_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/threshold_check_spec.rb
/usr/lib64/ruby/gems/2.3.0/gems/cane-2.6.2/spec/violation_formatter_spec.rb
/usr/lib64/ruby/gems/2.3.0/specifications/cane-2.6.2.gemspec

%files bin
%defattr(-,root,root,-)
/usr/bin/cane
